### ISSUE TITLE
Gradle project build fails on libc++_shared.so conflicts.

### ISSUE THREAD

**Issue by incubus370** [facebookincubator/fbjni#90] opened 2023-10-19 17:28 UTC
## Issue description

Usage of fbjni in conjuction with other libraries can cause conflicts of libc++_shared.so

![image](https://github.com/facebookincubator/fbjni/assets/14973293/0f97f767-5b07-487d-bc4e-18bbd33e30d2)

Conflicts can be resolved using

```
packagingOptions {
        pickFirst "lib/armeabi-v7a/libc++_shared.so"
        pickFirst "lib/arm64-v8a/libc++_shared.so"
        pickFirst "lib/x86/libc++_shared.so"
        pickFirst "lib/x86_64/libc++_shared.so"
    }
```

but such trick causes crash in runtime, because any dependency can get incompatible version of c++ shared library.

```
java.lang.UnsatisfiedLinkError: Bad JNI version returned from JNI_OnLoad in "/data/app/~~ZbHqrsKgKEnQcU1uwQ4pnw==/foo.bar.baz-macXtsVqrzK5TJV017tYQw==/HTTP://WEBADDRESS.ELIDED!/lib/arm64-v8a/HTTP://WEBADDRESS.ELIDED": 0
	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
	at java.lang.System.loadLibrary(System.java:1664)
```

libjni should be compiled using static libc++ and published in maven.

## System Info

Linux

**Comment by cortinico** [comment] 2023-10-20 20:21
Basically a duplicate of #69

**Comment by incubus370** [comment] 2023-10-20 20:32
> Basically a duplicate of #69

Yeah, same pain =)

**Comment by cortinico** [comment] 2023-10-20 20:55
On then we can close this one and keep the conversation there

**Closed by cortinico** 2023-10-20 20:55 UTC
